######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 20 21:47:41 2012
######################################################################

TEMPLATE = app
TARGET = testsubsonic
DEPENDPATH += .
INCLUDEPATH += .

QT += network
CONFIG += link_pkgconfig debug
PKGCONFIG += QJson

# Input
HEADERS += testclass.h \
           ../libsubsonic/subsonic.h \
           ../libsubsonic/artistfolder.h \
           ../libsubsonic/songobject.h
SOURCES += main.cpp \
           testclass.cpp \
           ../libsubsonic/subsonic.cpp \
           ../libsubsonic/artistfolder.cpp \
           ../libsubsonic/songobject.cpp
