# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       usubsonic
Summary:    qt/qml subsonic client
Version:	0.0.1
Release:    1
Group:      System/Base
License:    GPL v2
URL:        git://gitorious.org/nobdy/genericobd2.git
Source0:    %{name}-%{version}.tar.bz2
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Requires: nobdy
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtXml)
BuildRequires:  pkgconfig(QtNetwork)
BuildRequires:  pkgconfig(QtScript)
BuildRequires:  pkgconfig(QJson)
BuildRequires:  pkgconfig(nobdy)

%description
subsonic client written in qt/qml

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
/usr/lib/*
# >> files
# << files




