######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 20 21:42:30 2012
######################################################################

TEMPLATE = lib
TARGET = subsonic

QT += network

CONFIG += link_pkgconfig
PKGCONFIG += QJson

DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += artistfolder.h songobject.h subsonic.h
SOURCES += artistfolder.cpp songobject.cpp subsonic.cpp
